import { Logger } from '@nestjs/common';
import { InjectModel } from '@nestjs/mongoose';
import { Model } from 'mongoose';
import { Vehicle } from 'src/module/vehicles/vehicle.schema';
import { VehicleStatus } from 'src/module/vehicles/vehicles.type';

export const VEHICLES_SEED: Partial<Vehicle>[] = [
  {
    plate: 'KAH2019',
    brand: 'FORD',
    model: 'KA',
    version: null,
    year: 2019,
    category: 'HATCH',
    fuel: 'FLEX',
    transmission: 'MANUAL',
    engineSizes: '1_0',
    seats: 5,
    doors: 4,
    color: 'PRETO',
    dailyRateCents: 12900,
    status: VehicleStatus.AVAILABLE,
    isActive: true,
    notes: null,
    imageUrls: ['imagem 9.png'],
    _schemaVersion: 1,
  },
  {
    plate: 'DUS2018',
    brand: 'RENAULT',
    model: 'DUSTER',
    version: null,
    year: 2018,
    category: 'SUV',
    fuel: 'FLEX',
    transmission: 'MANUAL',
    engineSizes: '1_6',
    seats: 5,
    doors: 4,
    color: 'VERMELHO',
    dailyRateCents: 18900,
    status: VehicleStatus.AVAILABLE,
    isActive: true,
    notes: null,
    imageUrls: ['imagem 15.png'],
    _schemaVersion: 1,
  },
  {
    plate: 'COM2020',
    brand: 'JEEP',
    model: 'COMPASS',
    version: null,
    year: 2020,
    category: 'SUV',
    fuel: 'FLEX',
    transmission: 'AUTOMATIC',
    engineSizes: '2_0',
    seats: 5,
    doors: 4,
    color: 'PRATA',
    dailyRateCents: 23900,
    status: VehicleStatus.AVAILABLE,
    isActive: true,
    notes: null,
    imageUrls: ['imagem 16.png'],
    _schemaVersion: 1,
  },
  {
    plate: 'TIG2021',
    brand: 'CAOA CHERY',
    model: 'TIGGO 8',
    version: null,
    year: 2021,
    category: 'SUV_GRANDE',
    fuel: 'GASOLINE',
    transmission: 'AUTOMATIC',
    engineSizes: '1_6',
    seats: 7,
    doors: 4,
    color: 'BRANCO',
    dailyRateCents: 28900,
    status: VehicleStatus.AVAILABLE,
    isActive: true,
    notes: null,
    imageUrls: ['imagem 18.png'],
    _schemaVersion: 1,
  },
  {
    plate: 'TCR2020',
    brand: 'VOLKSWAGEN',
    model: 'T-CROSS',
    version: null,
    year: 2020,
    category: 'CROSSOVER',
    fuel: 'FLEX',
    transmission: 'AUTOMATIC',
    engineSizes: '1_0',
    seats: 5,
    doors: 4,
    color: 'BRANCO',
    dailyRateCents: 21900,
    status: VehicleStatus.AVAILABLE,
    isActive: true,
    notes: null,
    imageUrls: ['imagem 19.png'],
    _schemaVersion: 1,
  },
  {
    plate: 'CAM2017',
    brand: 'CHEVROLET',
    model: 'CAMARO',
    version: null,
    year: 2017,
    category: 'COUPE',
    fuel: 'GASOLINE',
    transmission: 'AUTOMATIC',
    engineSizes: '6_2',
    seats: 4,
    doors: 2,
    color: 'CINZA',
    dailyRateCents: 49900,
    status: VehicleStatus.AVAILABLE,
    isActive: true,
    notes: null,
    imageUrls: ['imagem 20.png'],
    _schemaVersion: 1,
  },
  {
    plate: 'SAV2018',
    brand: 'VOLKSWAGEN',
    model: 'SAVEIRO',
    version: null,
    year: 2018,
    category: 'PICAPE_LEVE_MEDIA',
    fuel: 'FLEX',
    transmission: 'MANUAL',
    engineSizes: '1_6',
    seats: 5,
    doors: 2,
    color: 'AZUL',
    dailyRateCents: 16900,
    status: VehicleStatus.AVAILABLE,
    isActive: true,
    notes: null,
    imageUrls: ['imagem 22.png'],
    _schemaVersion: 1,
  },
  {
    plate: 'STR2016',
    brand: 'FIAT',
    model: 'STRADA',
    version: null,
    year: 2016,
    category: 'PICAPE_LEVE',
    fuel: 'FLEX',
    transmission: 'MANUAL',
    engineSizes: '1_4',
    seats: 2,
    doors: 2,
    color: 'PRATA',
    dailyRateCents: 15900,
    status: VehicleStatus.AVAILABLE,
    isActive: true,
    notes: null,
    imageUrls: ['imagem 23.png'],
    _schemaVersion: 1,
  },
  {
    plate: 'TOR2016',
    brand: 'FIAT',
    model: 'TORO',
    version: null,
    year: 2016,
    category: 'PICAPE_MEDIA',
    fuel: 'FLEX',
    transmission: 'AUTOMATIC',
    engineSizes: '1_8',
    seats: 5,
    doors: 4,
    color: 'PRATA',
    dailyRateCents: 23900,
    status: VehicleStatus.AVAILABLE,
    isActive: true,
    notes: null,
    imageUrls: ['imagem 25.png'],
    _schemaVersion: 1,
  },
  {
    plate: 'KAS2019',
    brand: 'FORD',
    model: 'KA SEDAN',
    version: null,
    year: 2019,
    category: 'SEDAN_COMPACTO',
    fuel: 'FLEX',
    transmission: 'MANUAL',
    engineSizes: '1_0',
    seats: 5,
    doors: 4,
    color: 'BRANCO',
    dailyRateCents: 13900,
    status: VehicleStatus.AVAILABLE,
    isActive: true,
    notes: null,
    imageUrls: ['imagem 26.png'],
    _schemaVersion: 1,
  },
  {
    plate: 'VER2019',
    brand: 'NISSAN',
    model: 'VERSA',
    version: null,
    year: 2019,
    category: 'SEDAN_MEDIO',
    fuel: 'FLEX',
    transmission: 'AUTOMATIC',
    engineSizes: '1_6',
    seats: 5,
    doors: 4,
    color: 'PRETO',
    dailyRateCents: 14900,
    status: VehicleStatus.AVAILABLE,
    isActive: true,
    notes: null,
    imageUrls: ['imagem 27.png'],
    _schemaVersion: 1,
  },
  {
    plate: 'JET2021',
    brand: 'VOLKSWAGEN',
    model: 'JETTA',
    version: null,
    year: 2021,
    category: 'SEDAN_GRANDE',
    fuel: 'GASOLINE',
    transmission: 'AUTOMATIC',
    engineSizes: '1_4',
    seats: 5,
    doors: 4,
    color: 'BRANCO',
    dailyRateCents: 29900,
    status: VehicleStatus.AVAILABLE,
    isActive: true,
    notes: null,
    imageUrls: ['imagem 28.png'],
    _schemaVersion: 1,
  },
  {
    plate: 'DOB2018',
    brand: 'FIAT',
    model: 'DOBLO',
    version: null,
    year: 2018,
    category: 'MINIVAN',
    fuel: 'FLEX',
    transmission: 'MANUAL',
    engineSizes: '1_8',
    seats: 7,
    doors: 4,
    color: 'BRANCO',
    dailyRateCents: 18900,
    status: VehicleStatus.AVAILABLE,
    isActive: true,
    notes: null,
    imageUrls: ['imagem 29.png'],
    _schemaVersion: 1,
  },
  {
    plate: 'FIO2017',
    brand: 'FIAT',
    model: 'FIORINO',
    version: null,
    year: 2017,
    category: 'UTILITARIO_LEVE',
    fuel: 'FLEX',
    transmission: 'MANUAL',
    engineSizes: '1_4',
    seats: 2,
    doors: 3,
    color: 'BRANCO',
    dailyRateCents: 14900,
    status: VehicleStatus.AVAILABLE,
    isActive: true,
    notes: null,
    imageUrls: ['imagem 30.png'],
    _schemaVersion: 1,
  },
  {
    plate: 'PAR2016',
    brand: 'PEUGEOT',
    model: 'PARTNER',
    version: null,
    year: 2016,
    category: 'UTILITARIO',
    fuel: 'FLEX',
    transmission: 'MANUAL',
    engineSizes: '1_6',
    seats: 2,
    doors: 4,
    color: 'CINZA',
    dailyRateCents: 15900,
    status: VehicleStatus.AVAILABLE,
    isActive: true,
    notes: null,
    imageUrls: ['imagem 31.png'],
    _schemaVersion: 1,
  },
  {
    plate: 'MIN2021',
    brand: 'MINI',
    model: 'COOPER',
    version: null,
    year: 2021,
    category: 'HATCH',
    fuel: 'GASOLINE',
    transmission: 'AUTOMATIC',
    engineSizes: '2_0',
    seats: 4,
    doors: 3,
    color: 'VERDE',
    dailyRateCents: 27900,
    status: VehicleStatus.AVAILABLE,
    isActive: true,
    notes: null,
    imageUrls: ['imagem 32.png'],
    _schemaVersion: 1,
  },
];

export class VehicleSeed {
  private readonly logger = new Logger(VehicleSeed.name);

  constructor(
    @InjectModel(Vehicle.name) private readonly Vehicles: Model<Vehicle>,
  ) {}
  async run(): Promise<void> {
    for (const vehicle of VEHICLES_SEED) {
      await this.Vehicles.updateOne(
        { plate: vehicle.plate, year: vehicle.year },
        {
          $setOnInsert: {
            ...vehicle,
            status: VehicleStatus.AVAILABLE,
            createdAt: new Date(),
          },
        },
        { upsert: true },
      );

      this.logger.log(`Admin user created: ${vehicle.plate}`);
    }
  }
}
